### ISSUE TITLE
Failing Travis build

### ISSUE THREAD

**Issue by hawkw** [alexandrialibrary/alexandria-frontend#19]
Travis is currently building pushes to this repo, but we have no Travis config file and it tries to build a nonexistent Ruby project, the default with no config file. This (of course) fails. We should either get Travis properly configured to test/lint our JS and so on, or disable the Travis builds for this repo. 

I'm not super familiar with the methods of testing and linting front-end code that are popular these days, so I'm assigning @redbassett to this issue. If we decide to just disable the Travis builds, let me know and I can go in and turn them off.

**Comment by redbassett** [comment]
I toggled on the "build only when `.travis.yaml` is present" option.

**Comment by hawkw** [comment]
Great. We should look into CI options for testing/linting our front-end code eventually.

**Comment by redbassett** [comment]
:+1:
