### ISSUE TITLE
Remove paths that shouldn't be in VCS

### ISSUE THREAD

**Issue by hawkw** [alexandrialibrary/alexandria-frontend#3]
As far as I know, the `bower_components/`, `js/`, and `css/` directories are all automatically generated, so they shouldn't be committed to VCS. We should probably remove these directories and add them to the `.gitignore`.

(Thanks to @arcticlight for pointing this out)

**Comment by redbassett** [comment]
This should be part of figuring out a standardized build system.

**Comment by hawkw** [comment]
Yeah, but the `bower_components/` dir at the very least is auto-generated by Bower, which it looks like we're definitely using?

**Comment by redbassett** [comment]
Yes, I am installing via bower. Yes, we should standardize these processes. I assume rather than using vendor directories we want to just `.gitignore` the bower default directory?

**Comment by hawkw** [comment]
Yes.
