### ISSUE TITLE
Decide on a build system

### ISSUE THREAD

**Issue by hawkw** [alexandrialibrary/alexandria-frontend#4]
I've heard good things about Gulp...

**Comment by hawkw** [comment]
Okay, I was thinking about this for a bit while kneading what will eventually be a loaf of rye bread this morning; probably my No. 2 idea-generating activity, after showering (as @redbassett knows), and here's what I think we want to do. 

Whatever build system we use here in this repo, that will be used only in dev, and therefore shouldn't minify anything, if possible. I think we ought to minify our web assets only from sbt. We can continue using wro4j for that as we have been, as it works acceptably. We minify only when packaging a release web archive, which is done using the sbt build script on the main (frontend) repo. We'll probably want to see if we can `git subtree` the `components/`, `coffee/`, and `css/` directory, plus all of our HTML files, directly into the main repo's `webapp/` directory and let sbt handle them. We will have to see if it's possible to get sbt to [vulcanize](https://www.polymer-project.org/0.5/articles/concatenating-web-components.html) our Polymer web components; if we can't do that, we'll have to do that step from the front-end repo's build system.

**Comment by redbassett** [comment]
So if the frontend team ships this repo with just the `scss` and `coffee` directories (not `css` or `js`), we'll let SBT handle put the stuff in the right place?

**Comment by hawkw** [comment]
That's what I'm thinking. I cannot seem to find an sbt plugin for vulcanizing Polymer webcomponents though, so the front-end team may have to do that (ooooor I could maybe try and write one myself).

**Comment by redbassett** [comment]
While it could be done manually, I would prefer to find a way to do it as part of SBT.

**Comment by hawkw** [comment]
> I would prefer to find a way to do it as part of SBT.

Me too! But it looks like we'd have to write a custom plugin to do this, and that would require me to learn how to write sbt plugins.

**Comment by hawkw** [comment]
I mean, I could just do it by running `vulcanize` as a shell command, but then it would have to be installed on the machine doing the build. Which is manageable I guess.

**Comment by redbassett** [comment]
So Gulp can also do things like JS linting, uglifying JS, and concatenating files. I'm currently setting it up to just do the SASS/Coffeescript compile and I'll leave this stuff to SBT, but we might want to make these Gulp tasks in the future.

**Comment by hawkw** [comment]
I just figured that having sbt do the uglify/minify would be the best way to separate between unminified JS/CSS in dev and fully minified in production. I'm happy to have Gulp handle JS linting if you want.

**Comment by redbassett** [comment]
Agreed, I don't want to uglify and minify on the frontend repo. Coffee linting might be good, but I don't really care right this moment.
