### ISSUE TITLE
Add humans.txt meta

### ISSUE THREAD

**Issue by redbassett** [alexandrialibrary/alexandria-frontend#5]
Add a meta link in the `index.html` document to the `humans.txt` file.

**Comment by hawkw** [comment]
We need a bunch of footer content that we're not currently rendering ("Alexandria vX.Y.Z" might be nice somewhere too...)

**Comment by redbassett** [comment]
Like footer on the site? Or in `humans.txt`? If on the site, new issue :wink:

**Comment by hawkw** [comment]
Footer on the site, including at the very least a link to `humans.txt`, the Alexandria version, and maybe some kind of copyleft meta. It'll go to its own issue

**Comment by redbassett** [comment]
TY
